ALTER TABLE books
    ADD BESTSELLER BOOLEAN DEFAULT FALSE;

DROP PROCEDURE IF EXISTS UpdateBestsellers;

DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
    DECLARE BOOKSRENTED, TBOOK_ID INT;
    DECLARE FINISHED INT DEFAULT 0;
    DECLARE ALL_BOOKS CURSOR FOR SELECT BOOK_ID FROM books;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
OPEN ALL_BOOKS;
WHILE (FINISHED = 0)
        DO
            FETCH ALL_BOOKS INTO TBOOK_ID;
SELECT COUNT(*)
FROM rents
WHERE BOOK_ID = TBOOK_ID
    INTO BOOKSRENTED;

IF (BOOKSRENTED > 2) THEN
UPDATE books
SET books.BESTSELLER = TRUE
WHERE BOOK_ID = TBOOK_ID;
COMMIT;
END IF;
END WHILE;
CLOSE ALL_BOOKS;
END $$

DELIMITER ;

CALL UpdateBestsellers();
